### ISSUE TITLE
Provide URL links from NCL gallery to GeoCAT gallery

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT-examples#115]
Install links at appropriate places on the NCL web site that point to GeoCAT gallery. Possible NCL pages to update include:

https://www.ncl.ucar.edu/Applications/
https://www.ncl.ucar.edu/Applications/list_ptypes.shtml

and **possibly** linking individual NCL examples to their Python counterparts.

There are some cryptic notes from Hallock on updating the static NCL web site:

NCL website

- Webpub.ucar.edu (needs real link)
- Ncl_doc repo on internal git.ucar.edu
- Need account on webpub
- “unw” script to copy files
- Most webpages are in “.xml” format, running the “unw” script converts them to .shtml and scp’s them to webpub
- “unw -t” copies to the test website https://test.ncl.ucar.edu (only available on internal network)

**Comment by michaelavs** [comment]
Both pages mentioned have been updated successfully/published. I will start looking into adding individual links and see how that may work out if it is possible

**Comment by michaelavs** [comment]
Majority of gallery examples have now been linked to NCL versions. Working on adding new examples as they are merged into the repo
