### ISSUE TITLE
Create pages in gallery describing common plot elements

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-examples#118]
It would be beneficial to add pages to the gallery site that discuss drawing latitude/longitude ticks on various projections, the different ways text can be formatted, using inset axes, drawing different line styles, etc. On these pages, relevant example plots can be linked. This would provide an easier way for users to find examples specific to manipulating a particular element of a plot versus sifting through examples sorted by plot type. 

The original discussion that prompted the addition of this issue can be found [here.](https://github.com/NCAR/GeoCAT-examples/pull/110#pullrequestreview-434294718)

**Comment by kafitzgerald** [comment]
I think there's some similar motivation behind [the github.com/NCAR/geocat-applications](https://github.com/NCAR/geocat-applications) and the Visualization Cookbook for Project Pythia.  

@jukent should we close this in favor of those efforts?

**Comment by jukent** [comment]
I agree. We want these basic plot structures in applications.
