### ISSUE TITLE
Provide examples for CAM-SE data

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-examples#125]
Provide plotting examples that work with CAM Spectral Element (SE) dynamical core. The SE core is described here:

https://www.earthsystemcog.org/projects/dcmip-2012/cam-se

Note, there may or may not exist plotting utilities in the Python ecosystem that currently support this grid decomposition.

**Comment by erogluorhan** [comment]
@anissa111 @michaelavs Let us spend some time on this topic to

1. Explore whether any plotting utilities already exist in the Python ecosystem
2. If yes, come up with an example script using those utilities
3. Otherwise, investigate possibilities to implement one

**Comment by erogluorhan** [comment]
This should be handled by UXarray (already a few issues, e.g. [#11](https://github.com/UXARRAY/uxarray/issues/11) and [#183](https://github.com/UXARRAY/uxarray/issues/183), about CAM-SE support exist there)
