### ISSUE TITLE
Updating Polyg_19 

### ISSUE THREAD

**Issue by michaelavs** [NCAR/GeoCAT-examples#216]
Updating Polyg_19 to create a faster running code

**Comment by michaelavs** [comment]
@hCraker I was wondering if you have any specific input on using shapefiles with Python? We are trying to reduce the amount of memory/time to run on polyg_19 as it causes our builds to fail for readthedocs. The code block causing issues is 
`
for shape in us.shapeRecords():

    if shape.record[3] == 'Alaska':
        plotRegion(shape, axin1, [None, 100], puertoRico=False, waterBody=False)
    elif shape.record[3] == 'Hawaii':
        plotRegion(shape, axin2, [-161, None], puertoRico=False, waterBody=False)
    else:
        plotRegion(shape, ax1, [None, None], puertoRico=False, waterBody=False)
` 
Which is around line 197.
I'm still pretty unsure on how to use shapefiles but noticed you had submitted shapefile_1, so if you have any ideas on how to make this block a bit more efficient, I am open to suggestions!

**Comment by clyne** [comment]
Hi Michaela,

The first step in solving any kind of performance problem like this is to try to narrow down the hotspot; the portion of the code that is taking the most time. The best way to do this is with a profiling tool of some sort. There may be better options, but cProfile is simple and may do the trick:

https://docs.python.org/2/library/profile.html
https://stackoverflow.com/questions/582336/how-can-you-profile-a-python-script

cProfile will tell you how much time is spent in a function call chain. I would start by profiling each call to the function in the above loop. You may get lucky and  find that one of the 'shapes' is an outlier. Failing that, you can start profiling individual calls within plotRegion to which particular segment of plotRegion is taking up most of the time. Once you've identified the bottleneck, then you can start thinking about how you might eliminate it. Perhaps it is inefficient code inside of plotRegion that could be restructured, or perhaps it is a function that plotRegion calls, and a different parameter to that function might change the behavior. 

In addition to cProfile - or another profiler - simply putting timers around segments of code to see how long they take can also be illuminating. Hope this helps!

cc: @erogluorhan
