### ISSUE TITLE
NCL_panel_6.py

### ISSUE THREAD

**Issue by wjjxjd** [NCAR/GeoCAT-examples#224]
ax = plt.axes(projection=ccrs.SouthPolarStereo())
How can I set the parameter gvutil.set_map_boundary(ax, [-180, 180], [0, 40], south_pad=1) so that only see the map of the Antarctic Circle?

**Comment by michaelavs** [comment]
I believe you will want to set the lat range to [-90,-40]. The applicable range of latitude values for this function is (-90,90) where negative values are southern hemisphere and positive values are in the northern hemisphere. Full documentation for the GeoCAT utility functions are found in the [GeoCAT-viz repository](https://github.com/NCAR/geocat-viz/blob/develop/src/util.py).

**Comment by wjjxjd** [comment]
In fact,I am very familiar with NCL's settings for projection. At the same time, I also have considerable Python language foundation. For example, in NCL_panel_6.py I set the parameter such asgvutil.set_map_boundary(axs[row][col], (-180, 180), (-90, -30), south_pad=0). But the picture is white, there has noting. Thanks!

**Comment by michaelavs** [comment]
Would you mind providing your full code for me to look at? There are a couple of things that may cause this, but I won't know for sure until I can see for my self. The most probable cause is not referencing the data correctly in the function call, but there could also be a bug in our utility function.

**Comment by wjjxjd** [comment]
"""
NCL_panel_6.py
===============
This script illustrates the following concepts:
   - Paneling four plots on a page
   - Adding white space around paneled plots

See following URLs to see the reproduced NCL plot & script:
    - Original NCL script: https://www.ncl.ucar.edu/Applications/Scripts/panel_6.ncl
    - Original NCL plot: https://www.ncl.ucar.edu/Applications/Images/panel_6_1_lg.png and https://www.ncl.ucar.edu/Applications/Images/panel_6_2_lg.png
Note:
    A different colormap was used in this example than in the NCL example
    because rainbow colormaps do not translate well to black and white formats,
    are not accessible for individuals affected by color blindness, and
    vary widely in how they are percieved by different people. See this
    `example <https://geocat-examples.readthedocs.io/en/latest/gallery/Colors/CB_Temperature.html#sphx-glr-gallery-colors-cb-temperature-py>`_
    for more information on choosing colormaps.
"""

###############################################################################
# Import packages:
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.contour as mcontour
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import numpy as np
import xarray as xr

#import geocat.datafiles as gdf
import geocat.viz.util as gvutil

###############################################################################
# Read in data:

# Open a netCDF data file using xarray default engine and load the data into xarrays
ds = xr.open_dataset('netcdf_files/h_avg_Y0191_D000.00.nc',decode_times=False)                  
data0 = ds.T.isel(time=0, drop=True).isel(z_t=0, drop=True)
data1 = ds.T.isel(time=0, drop=True).isel(z_t=5, drop=True)
data2 = ds.S.isel(time=0, drop=True).isel(z_t=0, drop=True)
data3 = ds.S.isel(time=0, drop=True).isel(z_t=3, drop=True)

data0 = gvutil.xr_add_cyclic_longitudes(data0, "lon_t")
data1 = gvutil.xr_add_cyclic_longitudes(data1, "lon_t")
data2 = gvutil.xr_add_cyclic_longitudes(data2, "lon_t")
data3 = gvutil.xr_add_cyclic_longitudes(data3, "lon_t")

data = [[data0, data1], [data2, data3]]

###############################################################################
# Plot without extra whitespace:
projection = ccrs.SouthPolarStereo()
fig, axs = plt.subplots(2, 2, figsize=(8, 8),
                        subplot_kw=dict(projection=projection))
# Format axes and inset axes for color bars
cax = np.empty((2, 2), dtype=plt.Axes)
for row in range(0, 2):
    for col in range(0, 2):
        # Add map features
        axs[row][col].add_feature(cfeature.LAND, facecolor='silver', zorder=2)
        axs[row][col].add_feature(cfeature.COASTLINE, linewidth=0.5, zorder=3)
        axs[row][col].add_feature(cfeature.LAKES, linewidth=0.5,
                                  edgecolor='black', facecolor='None',
                                  zorder=4)

        # Add gridlines
        gl = axs[row][col].gridlines(ccrs.PlateCarree(), draw_labels=False,
                                     color='gray', linestyle="--", zorder=5)
        gl.xlocator = mticker.FixedLocator(np.linspace(-180, 150, 12))

        # Add latitude and longitude labels
        x = np.arange(0, 360, 30)
        # Array specifying 8S, this makes an offset from the circle boundary
        # which lies at the equator
        y = np.full_like(x, -8)
        labels = ['0', '30E', '60E', '90E', '120E', '150E', '180',
                  '150W', '120W', '90W', '60W', '30W']
        for x, y, label in zip(x, y, labels):
            if label == '180':
                axs[row][col].text(x, y, label, fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='top',
                                   transform=ccrs.Geodetic())
            elif label == '0':
                axs[row][col].text(x, y, label, fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='bottom',
                                   transform=ccrs.Geodetic())
            else:
                axs[row][col].text(x, y, label, fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='center',
                                   transform=ccrs.Geodetic())

        # Set boundary of plot to be circular
        gvutil.set_map_boundary(axs[row][col], (-180, 180), (-90, -30),
                                south_pad=0)
        # Create inset axes for color bars
        cax[row][col] = inset_axes(axs[row][col], width='5%', height='100%',
                                   loc='lower right',
                                   bbox_to_anchor=(0.175, 0, 1, 1),
                                   bbox_transform=axs[row][col].transAxes,
                                   borderpad=0)
# Import color map
cmap = "magma"

# Plot filled contours
contour = np.empty((2, 2), dtype=mcontour.ContourSet)
contour[0][0] = data[0][0].plot.contourf(ax=axs[0][0],
                                         cmap=cmap,
                                         levels=np.arange(-2, 34, 2),
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[0][1] = data[0][1].plot.contourf(ax=axs[0][1],
                                         cmap=cmap,
                                         levels=np.arange(-4, 30, 2),
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[1][0] = data[1][0].plot.contourf(ax=axs[1][0],
                                         cmap=cmap,
                                         levels=15,
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[1][1] = data[1][1].plot.contourf(ax=axs[1][1],
                                         cmap=cmap,
                                         levels=12,
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)

# Plot contour lines
data[0][0].plot.contour(ax=axs[0][0],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=np.arange(-2, 34, 2),
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[0][1].plot.contour(ax=axs[0][1],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=np.arange(-4, 30, 2),
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[1][0].plot.contour(ax=axs[1][0],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=15,
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[1][1].plot.contour(ax=axs[1][1],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=12,
                        transform=ccrs.PlateCarree(),
                        zorder=1)

# Create colorbars and reduce the font size
for row in range(0, 2):
    for col in range(0, 2):
        cbar = plt.colorbar(contour[row][col], cax=cax[row][col])
        cbar.ax.tick_params(labelsize=7)

# Format titles for each subplot
for row in range(0, 2):
    for col in range(0, 2):
        axs[row][col].set_title(data[row][col].long_name, loc='left',
                                fontsize=7, pad=20)
        axs[row][col].set_title(data[row][col].units, loc='right',
                                fontsize=7, pad=20)

plt.show()

###############################################################################
# Plot with extra whitespace:
#
# The keyword argument ``gridspec_kw`` accepts a dictionary with keywords passed
# to the GridSpec constructor used to create the grid the subplots are placed
# on. See the documentation for `GridSpec <https://matplotlib.org/3.2.2/api/_as_gen/matplotlib.gridspec.GridSpec.html#matplotlib.gridspec.GridSpec>`_
# for more information on how to manipulate the gridlayout.

projection = ccrs.SouthPolarStereo()
fig, axs = plt.subplots(2, 2, figsize=(8, 8), gridspec_kw=(dict(wspace=0.5)),
                        subplot_kw=dict(projection=projection))
# Everything beyond this is the same code for the example without extra white space
#

# Format axes and inset axes for color bars
cax = np.empty((2, 2), dtype=plt.Axes)
for row in range(0, 2):
    for col in range(0, 2):
        # Add map features
        axs[row][col].add_feature(cfeature.LAND, facecolor='silver', zorder=2)
        axs[row][col].add_feature(cfeature.COASTLINE, linewidth=0.5, zorder=3)
        axs[row][col].add_feature(cfeature.LAKES, linewidth=0.5,
                                  edgecolor='black', facecolor='None',
                                  zorder=4)

        # Add gridlines
        gl = axs[row][col].gridlines(ccrs.PlateCarree(), draw_labels=False,
                                     color='gray', linestyle="--", zorder=5)
        gl.xlocator = mticker.FixedLocator(np.linspace(-180, 150, 12))

        # Add latitude and longitude labels
        x = np.arange(0, 360, 30)
        # Array specifying 8S, this makes an offset from the circle boundary
        # which lies at the equator
        y = np.full_like(x, -8)
        labels = ['0', '30E', '60E', '90E', '120E', '150E', '180',
                  '150W', '120W', '90W', '60W', '30W']
        for x, y, label in zip(x, y, labels):
            if label == '180':
                axs[row][col].text(x, y, label, fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='top',
                                   transform=ccrs.Geodetic())
            elif label == '0':
                axs[row][col].text(x, y, label, fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='bottom',
                                   transform=ccrs.Geodetic())
            else:
                axs[row][col].text(x, y, label, fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='center',
                                   transform=ccrs.Geodetic())

        # Set boundary of plot to be circular
        gvutil.set_map_boundary(axs[row][col], (-180, 180), (-90, -30),
                                south_pad=0)
        # Create inset axes for color bars
        cax[row][col] = inset_axes(axs[row][col], width='5%', height='100%',
                                   loc='lower right',
                                   bbox_to_anchor=(0.175, 0, 1, 1),
                                   bbox_transform=axs[row][col].transAxes,
                                   borderpad=0)
# Import color map
cmap = "magma"

# Plot filled contours
contour = np.empty((2, 2), dtype=mcontour.ContourSet)
contour[0][0] = data[0][0].plot.contourf(ax=axs[0][0],
                                         cmap=cmap,
                                         levels=np.arange(-2, 34, 2),
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[0][1] = data[0][1].plot.contourf(ax=axs[0][1],
                                         cmap=cmap,
                                         levels=np.arange(-4, 30, 2),
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[1][0] = data[1][0].plot.contourf(ax=axs[1][0],
                                         cmap=cmap,
                                         levels=15,
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[1][1] = data[1][1].plot.contourf(ax=axs[1][1],
                                         cmap=cmap,
                                         levels=12,
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)

# Plot contour lines
data[0][0].plot.contour(ax=axs[0][0],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=np.arange(-2, 34, 2),
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[0][1].plot.contour(ax=axs[0][1],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=np.arange(-4, 30, 2),
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[1][0].plot.contour(ax=axs[1][0],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=15,
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[1][1].plot.contour(ax=axs[1][1],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=12,
                        transform=ccrs.PlateCarree(),
                        zorder=1)

# Create colorbars and reduce the font size
for row in range(0, 2):
    for col in range(0, 2):
        cbar = plt.colorbar(contour[row][col], cax=cax[row][col])
        cbar.ax.tick_params(labelsize=7)

# Format titles for each subplot
for row in range(0, 2):
    for col in range(0, 2):
        axs[row][col].set_title(data[row][col].long_name, loc='left',
                                fontsize=7, pad=20)
        axs[row][col].set_title(data[row][col].units, loc='right',
                                fontsize=7, pad=20)

plt.show()
I just changed two points, one is to set the projection and latitude, and the other is that I manually downloaded the data. What confuses me is that I also tried NCL_conOncon_5.py example. They are ineffective in setting the Antarctic projection.

**Comment by michaelavs** [comment]
The first thing I noticed in your code is that you have the map boundary points in parentheses not brackets. Try switching those first and let me know if that changes the outcome. I did try using this switch in the coonOncon_5 projection as well and noticed that it will plot for -90 through -40, so this may be a bug for us to look into. But for the time being, try the change I recommended and I will continue looking into the possible bug in the code

**Comment by wjjxjd** [comment]
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.contour as mcontour
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import numpy as np
import xarray as xr

import geocat.viz.util as gvutil



# Open a netCDF data file using xarray default engine and load the data into xarrays
ds = xr.open_dataset("netcdf_files/h_avg_Y0191_D000.00.nc",
                     decode_times=False)

data0 = ds.T.isel(time=0, drop=True).isel(z_t=0, drop=True)
data1 = ds.T.isel(time=0, drop=True).isel(z_t=5, drop=True)
data2 = ds.S.isel(time=0, drop=True).isel(z_t=0, drop=True)
data3 = ds.S.isel(time=0, drop=True).isel(z_t=3, drop=True)

data0 = gvutil.xr_add_cyclic_longitudes(data0, "lon_t")
data1 = gvutil.xr_add_cyclic_longitudes(data1, "lon_t")
data2 = gvutil.xr_add_cyclic_longitudes(data2, "lon_t")
data3 = gvutil.xr_add_cyclic_longitudes(data3, "lon_t")

data = [[data0, data1], [data2, data3]]



projection = ccrs.SouthPolarStereo()
fig, axs = plt.subplots(2,
                        2,
                        figsize=(8, 8),
                        subplot_kw=dict(projection=projection))

# Format axes and inset axes for color bars
cax = np.empty((2, 2), dtype=plt.Axes)
for row in range(0, 2):
    for col in range(0, 2):
        # Add map features
        axs[row][col].add_feature(cfeature.LAND, facecolor='silver', zorder=2)
        axs[row][col].add_feature(cfeature.COASTLINE, linewidth=0.5, zorder=3)
        axs[row][col].add_feature(cfeature.LAKES,
                                  linewidth=0.5,
                                  edgecolor='black',
                                  facecolor='None',
                                  zorder=4)

        # Add gridlines
        gl = axs[row][col].gridlines(ccrs.PlateCarree(),
                                     draw_labels=False,
                                     color='gray',
                                     linestyle="--",
                                     zorder=5)
        gl.xlocator = mticker.FixedLocator(np.linspace(-180, 150, 12))

        # Add latitude and longitude labels
        x = np.arange(0, 360, 30)
        # Array specifying 8S, this makes an offset from the circle boundary
        # which lies at the equator
        y = np.full_like(x, -8)
        labels = [
            '0', '30E', '60E', '90E', '120E', '150E', '180', '150W', '120W',
            '90W', '60W', '30W'
        ]
        for x, y, label in zip(x, y, labels):
            if label == '180':
                axs[row][col].text(x,
                                   y,
                                   label,
                                   fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='top',
                                   transform=ccrs.Geodetic())
            elif label == '0':
                axs[row][col].text(x,
                                   y,
                                   label,
                                   fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='bottom',
                                   transform=ccrs.Geodetic())
            else:
                axs[row][col].text(x,
                                   y,
                                   label,
                                   fontsize=7,
                                   horizontalalignment='center',
                                   verticalalignment='center',
                                   transform=ccrs.Geodetic())

        # Set boundary of plot to be circular
        gvutil.set_map_boundary(axs[row][col], (-180, 180), (-90, -30),
                                south_pad=0)
        # Create inset axes for color bars
        cax[row][col] = inset_axes(axs[row][col],
                                   width='5%',
                                   height='100%',
                                   loc='lower right',
                                   bbox_to_anchor=(0.175, 0, 1, 1),
                                   bbox_transform=axs[row][col].transAxes,
                                   borderpad=0)
# Import color map
cmap = "magma"

# Plot filled contours
contour = np.empty((2, 2), dtype=mcontour.ContourSet)
contour[0][0] = data[0][0].plot.contourf(ax=axs[0][0],
                                         cmap=cmap,
                                         levels=np.arange(-2, 34, 2),
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[0][1] = data[0][1].plot.contourf(ax=axs[0][1],
                                         cmap=cmap,
                                         levels=np.arange(-4, 30, 2),
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[1][0] = data[1][0].plot.contourf(ax=axs[1][0],
                                         cmap=cmap,
                                         levels=15,
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)
contour[1][1] = data[1][1].plot.contourf(ax=axs[1][1],
                                         cmap=cmap,
                                         levels=12,
                                         transform=ccrs.PlateCarree(),
                                         add_colorbar=False,
                                         zorder=0)

# Plot contour lines
data[0][0].plot.contour(ax=axs[0][0],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=np.arange(-2, 34, 2),
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[0][1].plot.contour(ax=axs[0][1],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=np.arange(-4, 30, 2),
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[1][0].plot.contour(ax=axs[1][0],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=15,
                        transform=ccrs.PlateCarree(),
                        zorder=1)
data[1][1].plot.contour(ax=axs[1][1],
                        colors='black',
                        linestyles='solid',
                        linewidths=0.5,
                        levels=12,
                        transform=ccrs.PlateCarree(),
                        zorder=1)

# Create colorbars and reduce the font size
for row in range(0, 2):
    for col in range(0, 2):
        cbar = plt.colorbar(contour[row][col], cax=cax[row][col])
        cbar.ax.tick_params(labelsize=7)

# Format titles for each subplot
for row in range(0, 2):
    for col in range(0, 2):
        axs[row][col].set_title(data[row][col].long_name,
                                loc='left',
                                fontsize=7,
                                pad=20)
        axs[row][col].set_title(data[row][col].units,
                                loc='right',
                                fontsize=7,
                                pad=20)

plt.show()
I'm sorry, I don't understand what you mean very much. I have deleted the code. In fact, I feel that it is a bug. How do you think you can modify it?

**Comment by michaelavs** [comment]
Your code originally had `gvutil.set_map_boundary(axs[row][col], (-180, 180), (-90, -30),
                            south_pad=0)' and it should have had `gvutil.set_map_boundary(axs[row][col], [-180, 180], [-90, -30],
                            south_pad=0)` due to formatting needs for the function. While investigating conOncon_5 (the code you mentioned you had experimented on), I found that there is potentially a bug when using the `SouthPolarStereo' projection instead of the `NorthPolarProjection` as the original code uses. From what I have seen so far is that the projection is using -90 as a "0" which means the referenced latitudes must be written as [-(lowest extent), 0]. So in your projections case, you would use [-40,0] to project from the exact south pole to the -40 line of latitude. With this version of the projection, the location of the longitude labels would need to be reformatted, but the projection does exist and only shows up to the -40 line of latitude.

**Comment by wjjxjd** [comment]
Thank you for your help, I have solved my confusion, and hope you can produce better works in the future

**Comment by cryohydromettools** [comment]
Dear @michaelavs  and developers,

I am trying plot sea ice concentration and surface temperature using NCL_panel_6.py. I was be able to setting the latitude between [-40, 0] using preview discussion. But my polar plot is very small (figure attached). How can I enlarge my polar plot? It is possible?

This is my all code.
```python

import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.contour as mcontour
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import numpy as np
import xarray as xr

import geocat.datafiles as gdf
import geocat.viz.util as gvutil

###############################################################################
# Read in data:

# Open a netCDF data file using xarray default engine and load the data into xarrays
#ds = xr.open_dataset(gdf.get("netcdf_files/h_avg_Y0191_D000.00.nc"),
#                     decode_times=False)
#ds = xr.open_dataset('../SEA/oisst-avhrr-v02r01.2016.nc')

ds = xr.open_dataset('../SEA/sea_ice_1979_2020.nc')

data0 = ds.SIC.isel(time=6, drop=True)
data0 = data0/10
data0 = data0.where(data0 <= 251, np.nan)
data0 = data0.where(data0 >= 15, np.nan)

data = data0

projection = ccrs.SouthPolarStereo()
fig, axs = plt.subplots(1,
                        1,
                        figsize=(6, 6),
                        gridspec_kw=(dict(wspace=0.2)),
                        subplot_kw=dict(projection=projection))


# Add map features
axs.add_feature(cfeature.LAND, facecolor='silver', zorder=2)
axs.add_feature(cfeature.COASTLINE, linewidth=0.5, zorder=3)
axs.add_feature(cfeature.LAKES,
                          linewidth=0.5,
                          edgecolor='black',
                          facecolor='None',
                          zorder=4)

# Add gridlines
gl = axs.gridlines(ccrs.PlateCarree(),
                             draw_labels=False,
                             color='gray',
                             linestyle="--",
                             zorder=5)
gl.xlocator = mticker.FixedLocator(np.linspace(-180, 150, 12))

# Add latitude and longitude labels
x = np.arange(0, 360, 30)
# Array specifying 8S, this makes an offset from the circle boundary
# which lies at the equator
y = np.full_like(x, -32)
labels = [
    '0', '30E', '60E', '90E', '120E', '150E', '180', '150W', '120W',
    '90W', '60W', '30W'
]
for x, y, label in zip(x, y, labels):
    if label == '180':
        axs.text(x,
                  y,
                  label,
                  fontsize=7,
                  horizontalalignment='center',
                  verticalalignment='top',
                  transform=ccrs.Geodetic())
    elif label == '0':
        axs.text(x,
                 y,
                 label,
                 fontsize=7,
                 horizontalalignment='center',
                 verticalalignment='bottom',
                 transform=ccrs.Geodetic())
    else:
        axs.text(x,
                 y,
                 label,
                 fontsize=7,
                 horizontalalignment='center',
                 verticalalignment='center',
                 transform=ccrs.Geodetic())

    # Set boundary of plot to be circular
    gvutil.set_map_boundary(axs, (-180, 180), (-40, 0),
                            south_pad=0)

# Import color map
cmap = "magma"

# Plot filled contours
contour = data.plot.contourf(ax=axs,
                             cmap=cmap,
                             levels=np.arange(0, 100, 10),
                             transform=ccrs.PlateCarree(),
                             add_colorbar=False,
                             zorder=0)

cbar = plt.colorbar(contour)

#plt.show()

fig.savefig('temp_5.png',dpi = 200, bbox_inches = 'tight', 
             pad_inches = 0.1, facecolor='w')


```


![temp_5](https://user-images.githubusercontent.com/61190871/168088716-0d2024d5-d02c-4040-aee8-69bf745377e2.png)


Regards,
Christian

**Comment by michaelavs** [comment]
Hi @cryohydromettools,
I believe you will want to edit either your `cbar = plt.colorbar(contour)` to include the keyword arg of "shrink" as seen in this [websites](https://www.adamsmith.haus/python/answers/how-to-change-matplotlib-color-bar-size-in-python) example (I would start somewhere around 0.5 and increase/decrease from there). Or you may find success by making your figsize parameter from `fig, axs = plt.subplots(1,
                        1,
                        figsize=(6, 6),
                        gridspec_kw=(dict(wspace=0.2)),
                        subplot_kw=dict(projection=projection))` larger. 

If I'm not mistaken, the sizing of the colorbar and plot are automatically generated which can lead to these weird scaling/sizing issues. Let me know if neither of those options work for you and I can take a closer look at the code!

**Comment by michaelavs** [comment]
Hi @cryohydromettools,
Is there somewhere I would be able to download the netCDF file you are using? It may help me with testing your code, but if not that's definitely fine too

**Comment by cryohydromettools** [comment]
Hi @michaelavs,

Sure, I am attaching an subset of the netCDF file that I am using. I am not attaching all file because this is very larger.
 
[sea_ice_1979_2020_subset.nc.tar.gz](https://github.com/NCAR/GeoCAT-examples/files/8681403/sea_ice_1979_2020_subset.nc.tar.gz)

**Comment by michaelavs** [comment]
Hi @cryohydromettools,
After playing around with a couple of other GeoCAT-examples recreations of similar plots to Panel_6, I found pretty much exactly what you did which is that you need to make the latitude range in `gvutil.set_map_boundary` smaller (I used 0,1) in order to make the projection larger. I don't have an explanation for you as to why this is the behavior, my best guess is that it has something to do with the projection being in the south pole and not the north, and that this case was not necessarily tested for during development (just based on the examples using this function in the GeoCAT-examples gallery). We have work planned for this upcoming summer for the GeoCAT-viz utility functions, so I will make sure this behavior is noted and looked into.
