### ISSUE TITLE
Colorbar `extend` and 'norm' parameters are deprecated since 3.3 and will be removed two minor releases later

### ISSUE THREAD

**Issue by hCraker** [NCAR/GeoCAT-examples#268]
`matplotlib` will no longer be using the `extend` and `norm` parameters for colorbars as stated [here](https://matplotlib.org/3.3.1/api/api_changes.html#effectless-parameters-of-figure-colorbar-and-matplotlib-colorbar-colorbar). We will need to address this in the following examples in the gallery. This list is current at the time of opening this issue and may need to be updated as other examples are added.

Examples that use `extend`:
[CB_Height.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Colors/CB_Height.html#sphx-glr-gallery-colors-cb-height-py)
[CB_Rain.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Colors/CB_Rain.html#sphx-glr-gallery-colors-cb-rain-py)
[CB_Temperature.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Colors/CB_Temperature.html#sphx-glr-gallery-colors-cb-temperature-py)
[NCL_lcnative_1_lg.py](https://geocat-examples.readthedocs.io/en/latest/gallery/MapProjections/NCL_lcnative_1_lg.html#sphx-glr-gallery-mapprojections-ncl-lcnative-1-lg-py)
[NCL_native_2.py](https://geocat-examples.readthedocs.io/en/latest/gallery/MapProjections/NCL_native_2.html#sphx-glr-gallery-mapprojections-ncl-native-2-py)
[NCL_proj_1.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Contours/NCL_proj_1.html)
[NCL_proj_3.py](https://geocat-examples.readthedocs.io/en/latest/gallery/MapProjections/NCL_proj_3_lg.html#sphx-glr-gallery-mapprojections-ncl-proj-3-lg-py)
[NCL_sat_3.py](https://geocat-examples.readthedocs.io/en/latest/gallery/MapProjections/NCL_sat_3.html#sphx-glr-gallery-mapprojections-ncl-sat-3-py)
[NCL_vector_1.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Vectors/NCL_vector_1.html)

Examples that use `norm`:
[NCL_overlay_6.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Overlays/NCL_overlay_6.html)

**Comment by michaelavs** [comment]
Hi Rose,
I've been looking into this issue and think I have found at least one fix for the warning. Currently for lcnative_1, the colorbar arguments were inside of contourf, which I believe to be the main problem for matplotlib 3.3.2. So as a fix, I moved the colorbar kwargs outside of the contourf call and no longer get the warning that this issue addresses. If you are ok with it, I would like to assign this issue to myself and open a PR and start making changes to the other files that will need to be updated.

**Comment by hCraker** [comment]
> Hi Rose,
> I've been looking into this issue and think I have found at least one fix for the warning. Currently for lcnative_1, the colorbar arguments were inside of contourf, which I believe to be the main problem for matplotlib 3.3.2. So as a fix, I moved the colorbar kwargs outside of the contourf call and no longer get the warning that this issue addresses. If you are ok with it, I would like to assign this issue to myself and open a PR and start making changes to the other files that will need to be updated.
> 
> edit: I actually just finished updating all of the files on the list, so I'm going to go ahead and self assign this to me and open a corresponding PR

That sounds good to me. Thank you for working on this.
