### ISSUE TITLE
Github actions update causing build failures

### ISSUE THREAD

**Issue by anissa111** [NCAR/GeoCAT-examples#292]
Github deprecated two commands used in ```actions/checkout@v1```,  ```add-path``` and ```set-env``` on November 16.

A GitHub Blog post can be found about the change here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by erogluorhan** [comment]
Yes, I was going to talk about this today, thanks a lot for bringing it together, Anissa! Apparently they took this action due to a security concern, but there seems to be a quick solution by setting some variables in Github actions config file.
