### ISSUE TITLE
Creating periodic checks of master branch

### ISSUE THREAD

**Issue by anissa111** [NCAR/GeoCAT-examples#294]
Over the last couple weeks, there have been a couple instances where something unrelated to code we developed in this repo breaking the master branch, when it appears to be fine based on the last merge and causing confusion when PR branches start failing.

I think we should run a periodic check on master instead of just when a new PR is merged. Maybe once a day at night or something.

@michaelavs @erogluorhan @pilotchute @hCraker let me know your thoughts!

**Comment by erogluorhan** [comment]
I agree. Here is the reference about [scheduled events](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events-schedule). 

Moreover, I think that we need to work on our event triggerers (push and pull_request_target on branches * currently) to 100% cover pushes from forked repos as well as avoiding multiple triggerings for teh same event (in favor of automatic code-formatter)

**Comment by anissa111** [comment]
> Moreover, I think that we need to work on our event triggerers (push and pull_request_target on branches * currently) to 100% cover pushes from forked repos as well as avoiding multiple triggerings for teh same event (in favor of automatic code-formatter)

Yeah, I 100% agree. I think we could use some time to reconsider how we're doing github checks as a team.

**Comment by hCraker** [comment]
I think this is an excellent idea. I don't know very much about how these checks work, but let me know if there is anything I can do to help.

**Comment by andersy005** [comment]
> I think this is an excellent idea. I don't know very much about how these checks work, but let me know if there is anything I can do to help.

@hCraker, it's a matter of adding the following in the `on` key section:

```yaml
 schedule:
     - cron: '0 0 * * *' # Daily “At 00:00”
```


https://github.com/NCAR/GeoCAT-examples/blob/40f05e2762248ec386376665ca68fe0d3514c162/.github/workflows/build.yml#L3


If you want to use a different schedule, you can use [crontab guru](https://crontab.guru/) to help generate your cron syntax
