### ISSUE TITLE
Plot example request: Taylor diagrams

### ISSUE THREAD

**Issue by sethmcg** [NCAR/GeoCAT-examples#323]
Taylor diagrams are commonly used for comparing the performance of different models.  It would be great to have a GeoCAT example of this kind of plot.

NCL example: http://www.ncl.ucar.edu/Applications/taylor.shtml

@erogluorhan @anissa111

**Comment by erogluorhan** [comment]
@michaelavs @anissa111 Can we please look into this?

**Comment by anissa111** [comment]
> @michaelavs @anissa111 Can we please look into this?

Yup absolutely!

**Comment by ZHUANSHI** [comment]
A quick search found the following links maybe interested in by guys using Python and/or R.

1.  https://cdat.llnl.gov/Jupyter-notebooks/vcs/Taylor_Diagrams/Taylor_Diagrams.html (Python)
2.  https://www.rdocumentation.org/packages/plotrix/versions/3.8-2/topics/taylor.diagram (for R) 
3.  https://stackoverflow.com/questions/69638487/how-to-create-side-by-side-plots-of-taylor-diagram-and-ggplot (for R/ggpot2)

In fact, there are a lot of other examples available online.

**Comment by anissa111** [comment]
Hello! 

Sorry it's not obvious from this issue, but we now have several Taylor Diagram examples in geocat-examples here: https://geocat-examples.readthedocs.io/en/latest/gallery/index.html#taylor-diagrams

These are implemented with new functionality in geocat-viz

**Comment by ZHUANSHI** [comment]
Yes. I also noticed the examples that you pointed out just after I posted my comments. sorry about it, I should check them first before posting.

**Comment by anissa111** [comment]
@ZHUANSHI No problem! I'm going to close this issue now.
