### ISSUE TITLE
panel _14

### ISSUE THREAD

**Issue by anissa111** [NCAR/GeoCAT-examples#335]
Description: 2x2 panel plot with contours and line plots

Related: [GeoCAT-examples panel plots](https://geocat-examples.readthedocs.io/en/latest/gallery/index.html#panels)

NCL Page: https://www.ncl.ucar.edu/Applications/panel.shtml
NCL Script: https://www.ncl.ucar.edu/Applications/Scripts/panel_14.ncl
NCL Plot: https://www.ncl.ucar.edu/Applications/Images/panel_14_lg.png

![image](https://user-images.githubusercontent.com/38434768/118033793-75b72c80-b326-11eb-942a-4d4e89df5ce5.png)

**Comment by Jiaqi-beep** [comment]
@anissa111 @michaelavs Hi!! I am having trouble with the log scales on the contour plot. Below is the plot when I set the y-axis to log scale, and it doesn't seem like the same scale as the original one (the tick 100000 should be approaching the middle of the y-axis). There are a couple other problems (minor and major tick marks) but I think figuring out the scale to X and Y axis should be the first step. Do you guys have a clue to what the scale should be? The original NCL script doesn't seem to specify this.
![image](https://user-images.githubusercontent.com/63561327/122416717-32179a00-cf46-11eb-9fc7-af58af2039c0.png)
