### ISSUE TITLE
NCL's bootstrapping examples already implemented somewhere and could be used here

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/GeoCAT-examples#353]
**Description** 
The most of NCL's bootstrapping examples have been implemented by Brian Medeiros of NCAR in a [single Jupyter notebook](https://github.com/brianpm/hacknostics/blob/master/Notebooks/bootstrapping_like_ncl.ipynb), and Brian is fine with us including them in the GeoCAT-examples gallery. [The html version of the notebook](https://brianpm.github.io/hacknostics/bootstrapping_like_ncl.html) can be also seen.

Please also investigate Brian's hacknostics repo for additional NCL examples.

**NCL plots and scripts**
[NCL Bootstrapping and resampling examples](http://ncl.ucar.edu/Applications/bootstrap.shtml)

**Comment by anissa111** [comment]
I'm going to close this for the following reasons:
- These functions would ideally be replicated in geocat-comp, not here in geocat-examples, and at this moment we can't prioritize that work.
- If we did implement these functions in geocat-comp, these notebooks would probably belong in the geocat-comp documentation
- Reformatting these notebooks to fit our templates in either repository might be more work that a complete reimplementation

If anyone wants a reimplementation of the bootstrapping functions separate from already existing implementations in the python ecosystem, I suggest they make an issue in geocat-comp.
