### ISSUE TITLE
Xarray workaround should be reverted when Xarray releases their bugfix version

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/GeoCAT-examples#389]
We had to exclude `NCL_xy_18.py` from deployment by simply renaming it to `NCL_xy_18.pyexclude` because of a compatibility issue Xarray's version 1.18.2 having with Pandas 1.3.0 (See [Xarray Issue](https://github.com/pydata/xarray/issues/5581)) to have our `main` branch up and running again as well as to get our outstanding PRs merged. Once Xarray releases their bugfix, we need not to forget re-deploying our  `NCL_xy_18.py`.

**Comment by erogluorhan** [comment]
@anissa111 @michaelavs Xarray released v0.19.0 that is said to be fixing the slicing problem mentioned in this issue. Could you please address this whenever available?

**Comment by anissa111** [comment]
> @anissa111 @michaelavs Xarray released v0.19.0 that is said to be fixing the slicing problem mentioned in this issue. Could you please address this whenever available?

I'm on it!
