### ISSUE TITLE
Unstructured Grid Plotting with CellFill method?

### ISSUE THREAD

**Issue by whannah1** [NCAR/GeoCAT-examples#400]
I'm a long time NCL/PyNGL user and I'm a huge fan of plotting unstructured grid data on the native grid. In fact, for E3SM development, using the native grid to plot has helped identify problems that are normally washed out when using regridded data. Specifically, I think it is especially valuable to have the "CellFill" mode available in NCL and PyNGL using user provided mesh information, usually from a SCRIP file that can be generated with NCO. 

**Note that this type of plot is NOT currently possible with matplotlib/cartopy.**

I'm a bit disappointed that I haven't heard/read any chatter about supporting this type of plot. I also didn't see anything acknowledging the lack of MPL support for this in any text describing the effort to put NCL/PyNGL into maintenance mode. I noticed another github issue (#272) talking about the generation of mesh data, but that also didn't acknowledge any plans for a cell fill mode with user provided mesh data. In my experience, Delaunay triangulation is not nearly as useful and is often more computationally burdensome.

With the move towards unstructured grids, along with the push for using finite volume physics grids in tandem with spectral element dynamics grids, I think it is VERY important to support this type of plot. So I'm hoping someone can either confirm that support for this is already planned or acknowledge that this is needed.

**Comment by erogluorhan** [comment]
Hi @whannah1 ,

Thanks a lot for sharing your thoughts about CellFIll thoroughly! 

For your reference, our efforts/discussions on UnstructuredGrids so far have been investigative, and we will still need to explore many things such as what capabilities and lacking functions MPL has, what plotting modes the existing unstructured grid visualizers used much, what performance issues (e.g. resolution) the existing solutions had, etc. Therefore, we. didn't put explicit information about specific functionalities such as CellFill into our docs describing NCL's maintenance mode. However, our goal is going to be implementing the solutions common in the unstructured grid data analysis and visualization (such as CellFill)in a scalable way in Scientific Python Ecosystem, either with using existing packages like MPL if possible or making our own implementation.

With that being said, experiences and thoughts such as yours in this issue will be much helpful for us when it comes to the actual implementation phase. I am not sure why you closed the issue on the same day though. Please let me know if you had any further findings.

I hope these help a bit. 

Best,

Orhan - GeoCAT

**Comment by whannah1** [comment]
@erogluorhan after posting I thought it might be more appropriate to post this on the geocat-comp repo, so I made an issue there with a similar write up ([Issue #165](https://github.com/NCAR/geocat-comp/issues/165)). 

I'm happy to help and do some testing/debugging when it comes to the actual implementation, so feel free to keep me in the loop.

**Comment by clyne** [comment]
I just wanted to add that the GeoCAT team has been awarded a three-year NSF grant to provide better support for unstructured grids. The project, called Raijin, should kick off in early fall. We should be making a formal announcement with additional details later this summer.

**Comment by erogluorhan** [comment]
> @erogluorhan after posting I thought it might be more appropriate to post this on the geocat-comp repo, so I made an issue there with a similar write up ([Issue #165](https://github.com/NCAR/geocat-comp/issues/165)).
> 
> I'm happy to help and do some testing/debugging when it comes to the actual implementation, so feel free to keep me in the loop.

Oh, okay, I missed that one. Yes, we'd definitely be happy to keep you in the loop!

Thanks @clyne for sharing Raijin news!
