### ISSUE TITLE
How to refer to geocat-viz in import statements

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/GeoCAT-examples#50]
In [station_2](https://geocat-examples.readthedocs.io/en/latest/auto_examples/Station/station_2.html#station-2) I use `import geocat.viz as gcv`, but @khallock suggested coming up with a different naming convention otherwise we'll end up with `import geocat.comp as gcc` and it's not a good idea to co-opt a widely-known name. So this is mostly a question to spawn discussion, although I suppose a PR that updates `station_2` would be a good way to close the issue.

One possibility is `import geocat.viz as gcviz`, though `import geocat.comp as gccomp` now combines the `gcc` compiler and the `omp` threading directives in its name... maybe `import geocat.viz as gc_viz` and `import geocat.comp as gc_comp`?

I should note that [vector_1](https://geocat-examples.readthedocs.io/en/latest/auto_examples/Vectors/vector_1.html#sphx-glr-auto-examples-vectors-vector-1-py) should be updated to use `geocat.viz`, and I'd like to get `vector_3` right from the get-go before merging #34

**Comment by mnlevy1981** [comment]
Strike that last sentence clause, it looks like maybe we'll get #34 (and #38) merged relying on `gcv` and then they can all be fixed when addressing this issue.

**Comment by clyne** [comment]
I agree colliding with gcc (or anything else that is widely used) would not be a good idea. But I'm not sure we need to strictly adhere to any naming rules. If 'gcv' works for geocat.viz I don't think that necessitates using 'gcc' for geocat-comp. How about gccm, or gcp if three letters is desirable? 

All that said I don't have a strong opinion on this :-)

**Comment by erogluorhan** [comment]
I will be walking through all of the functions to refactor them for standardization, will keep this discussion in my mind, and will hopefully let you know of a reasonable import naming convention. I had used `import geocat.viz as gviz` and `import geocat.datafiles as gdf` in my `NCL_conLev_4.py` by the way.

**Comment by mnlevy1981** [comment]
@erogluorhan I'm working on an update for the vector plots (besides the `geocat.viz` issue being discussed here, I want to add some additional comments)... but when @khallock updated `vector_1` in #53 he used

```python
from geocat.viz.util import add_lat_lon_ticklabels, nclize_axis, truncate_colormap
```

and I think that's a nice look for now... I assume that the logic behind the choice was to be minimally invasive (i.e. not change the cells that actually call those functions), but I don't think we need to use `gviz.utils.____` until more functions get added to the package.

**Comment by erogluorhan** [comment]
Currently, it seems to be working well as follows in several scripts:

`from geocat.viz import util as gvutil`
