### ISSUE TITLE
Add viz as upstream dependency

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-examples#507]
Have a main and upstream-dev branch that tests for incoming changes from viz as well as other dependencies

Related to https://github.com/NCAR/geocat-viz/issues/128

**Comment by kafitzgerald** [comment]
Was reminded about the importance of having this in the latest bit of work on viz/examples.  

I'd love to get this in place ASAP and happy to do it if that's helpful.

**Comment by jukent** [comment]
That'd be great thanks @kafitzgerald

**Comment by kafitzgerald** [comment]
We should also do something along the lines of what's mentioned in NCAR/geocat-comp#503
