### ISSUE TITLE
geocat-examples is failing upstream CI

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/geocat-examples#510]
geocat-examples is failing upstream CI because of an expired deprecation in numpy.  

It looks like these are all impacted, but the error is the same:
NCL_conwomap_3.py
NCL_meteo_1.py
moc_global_atl_example.py

Relevant info from the logs below.

> AttributeError: module 'numpy' has no attribute 'int'.
> 
> `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> 
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
> 
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by jukent** [comment]
Another reason to have geocat-examples have its own upstream CI tests :)
