### ISSUE TITLE
Notebook example's format seems like broken after the new docs style

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-examples#519]
**Describe the bug**
The plots in this [notebook](https://geocat-examples.readthedocs.io/en/latest/gallery-notebooks/Datashader/MPAS_Datashader_Trimesh.html) needs to have a better formatting for better readibility

**To Reproduce**
Steps to see the behavior:
1. Go to https://geocat-examples.readthedocs.io/en/latest/gallery-notebooks/Datashader/MPAS_Datashader_Trimesh.html
2. Check the plots through the end of the page, e.g. check out the screenshot below.

**Expected behavior**
Maybe fit the plot into the screen/column size?

**Screenshots**
<img width="973" alt="image" src="https://github.com/NCAR/geocat-examples/assets/32553057/fd9e968c-53dd-473d-af05-256880898187">

**Comment by kafitzgerald** [comment]
Yeah, it looks like the height and width in pixels are specified manually in the first cell at the moment, but Holoviews has some responsive / dynamic options that could help: https://holoviews.org/user_guide/Plotting_with_Bokeh.html#responsive. 

I can give this a shot if nobody is already looking into it.
