### ISSUE TITLE
CI still failing on linint2

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-examples#527]
```  
File "/Users/runner/work/geocat-examples/geocat-examples/GeoCAT-comp-examples/matplotlib/linint2_example.py", line 100, in <module>
after excluding 0 files that had previously been run (based on MD5).
    p = newsst.plot.contourf(ax=ax, **plot_options)

AttributeError: 'NoneType' object has no attribute 'plot'
```

**Comment by kafitzgerald** [comment]
Yeah, it looks like it's using an old cached environment.  I'll go in and delete and rerun.

**Comment by kafitzgerald** [comment]
And re-running a workflow uses the same old commit 🤦🏻‍♀️  so it fails anyway.  

I'll keep an eye on this and close it out once I confirm it's working.

**Comment by jukent** [comment]
Oh good point. Maybe tonight's CI run will work then? I'll look when I get back if this is still an issue.

**Comment by jukent** [comment]
Seems to be working now!
