### ISSUE TITLE
Data Visualization Pythia Cookbook

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-examples#531]
Create a data visualization Pythia cookbook to move none NCL-gallery items out of geocat-examples

https://github.com/jukent/advanced-viz-cookbook/tree/geocat-viz

**Comment by jukent** [comment]
Working on this Cookbook: https://github.com/ProjectPythia/advanced-viz-cookbook

Creating resources to use in AMS and AGU short courses

**Comment by erogluorhan** [comment]
Just to make sure, if we are really aiming at moving some gallery items out of this gallery, please list their names and why clearly.
