### ISSUE TITLE
Update assets to comply with the New NSF Branding Theme

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-examples#583]
Update documentation site, pages, etc. to reflect the NSF branding policy changes (e.g. NSF NCAR) wherever applicable, e.g. logos,  text, etc.

**Comment by kafitzgerald** [comment]
Similarly to viz, it looks like we just need to update the citation info.

**Comment by kafitzgerald** [comment]
I just went ahead and put in a PR (NCAR/geocat-viz#191) for the corresponding issue on geocat-viz.  Let me know if you'd like me to make those changes here as well once that's reviewed/approved.  I requested a review from you so we can make sure we're all on the same page.

**Comment by erogluorhan** [comment]
Yes, that PR looked good, please feel free to do that similarly here.
