### ISSUE TITLE
proj_1 (Mollweide projection)

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT-examples#62]
Description:Drawing filled contours over a Mollweide map

Script URL: https://www.ncl.ucar.edu/Applications/Scripts/proj_1.ncl

Plot URL: https://www.ncl.ucar.edu/Applications/Images/proj_1_lg.png

Category: Map projections

**Comment by hCraker** [comment]
It looks like this issue has already been solved and the example file is located at Plots/Contours/NCL_proj_1.py in the master branch. Is this example finished? If so, can one of you mark this as closed? Thanks!

@jukent @erogluorhan @khallock

**Comment by jukent** [comment]
@hCraker I believe you are correct. I will close this issue.

**Comment by erogluorhan** [comment]
Good catch, @hCraker !
Thanks, @jukent !
