### ISSUE TITLE
Move generate_2d_array() Implementation to geocat-viz

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-examples#80]
PR #71 (`NCL_panel_35`) implements and uses `generate_2d_array` function from **NCL** capabilities. Indeed, this function should be implemented under **geocat-comp**. its implementation should be removed from `NCL_panel_35` and called from geocat-comp instead.

There is a Python version of `generate_2d_array` function in PyNGL (within the file ./src/ngl/__init__.py) found in the PyNGL repo: https://github.com/NCAR/pyngl.  The code would need to be cleaned up before it is included it in GeoCAT.

**Comment by clyne** [comment]
When the time comes we might want to consider whether this function go in geocat-comp or in geocat-viz

**Comment by erogluorhan** [comment]
Agreed.

**Comment by jukent** [comment]
See @mnlevy1981 's comment on #71 on an error stemming from reusing the midpoint definition. 
https://github.com/NCAR/GeoCAT-examples/pull/71/files/db20067be9c054afffff03c3ae031fb73912ea35#r431287376

**Comment by jukent** [comment]
@anissa111 do you feel this should be moved into comp?

**Comment by anissa111** [comment]
> @anissa111 do you feel this should be moved into comp?

I agree it probably shouldn't be in an examples script, but I'm not sure about needing a comp implementation. Let's talk about it next week at the comp meeting?

**Comment by jukent** [comment]
Makes sense. Perhaps it should be in viz?

**Comment by jukent** [comment]
Going to add this to viz for now to get the function callable. We can move it later if we decide to, as there isn't a natural fit within a comp module.

**Comment by jukent** [comment]
Closing in favor of #558
