### ISSUE TITLE
colormap comparison plot

### ISSUE THREAD

**Issue by clyne** [NCAR/GeoCAT-examples#92]
Produce one or more montage (multiple subpanels) plots as necessary that illustrate different colormaps applied to the same data. One of the colormaps should be the rainbow as an illustration of what NOT to use. 

Choose data sets that are appropriate for different color map types (e.g. temperature or velocity components for divergent maps, a field such with no "special values" such as rain fall for a "color scale" map).

The choice of maps should be based on current best practices. See

http://www.kennethmoreland.com/color-advice/

and references therein

**Comment by michaelavs** [comment]
@clyne should this be a part of the Plots sub directory, gallery subdirectory, or a new subdirectory completely? I am about to push the first version of a temperature projection but want to make sure we're all on the same page where this category of plots will go

**Comment by clyne** [comment]
How about we just create a new sub directory under Plots called "Color"?
